package:
  name: opencv3
  version: 3.1.0

source:
  fn: opencv-3.1.0.tar.gz
  url: https://github.com/Itseez/opencv/archive/3.1.0.tar.gz
  sha256: f00b3c4f42acda07d89031a2ebb5ebe390764a133502c03a511f67b78bbd4fbf
  
  patches:
    - cap_mpjpeg_decoder.patch  # [win]
    - no_rpath.patch

requirements:
  build:
   - python
   - cmake
   - hdf5 1.8.15.1  # [osx]
   - numpy
   - eigen 3.2.7
   - tbb 4.3_20141023  # [osx]
   - msinttypes r26  # [win and py<35]

  run:
   - python
   - numpy
   - hdf5 1.8.15.1  # [osx]
   - tbb 4.3_20141023  # [osx]

test:
  imports:
    - cv2
    - cv2.xfeatures2d

about:
  home: http://opencv.org/
  license: BSD
